### ISSUE TITLE
District's can't load in the Modern Anesidora Branch

### ISSUE THREAD

**Issue by GracieLovelight** [Arbitrium-Studios/Open-Fantasy#27]
```
Traceback (most recent call last):
  File "C:\Panda3D-1.11.0-x64\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Panda3D-1.11.0-x64\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\zacha\SynologyDrive\Toontown Fantasy\open-fantasy\toontown\ai\AIStart.py", line 38, in <module>
    simbase.air.connect(host, port)
  File "C:\Panda3D-1.11.0-x64\direct\distributed\AstronInternalRepository.py", line 599, in connect
    ConnectionRepository.connect(self, [url],
  File "C:\Panda3D-1.11.0-x64\direct\distributed\ConnectionRepository.py", line 512, in connect
    successCallback(*successArgs)
  File "C:\Panda3D-1.11.0-x64\direct\distributed\AstronInternalRepository.py", line 620, in __connected
    self.handleConnected()
  File "C:\Users\zacha\SynologyDrive\Toontown Fantasy\open-fantasy\toontown\ai\ToontownAIRepository.py", line 140, in handleConnected
    self.district.generateWithRequiredAndId(self.districtId, self.getGameDoId(), OTP_ZONE_ID_DISTRICTS)
  File "C:\Panda3D-1.11.0-x64\direct\distributed\DistributedObjectAI.py", line 413, in generateWithRequiredAndId
    self.air.generateWithRequiredAndId(self, doId, parentId, zoneId, optionalFields)
  File "C:\Panda3D-1.11.0-x64\direct\distributed\AstronInternalRepository.py", line 570, in generateWithRequiredAndId
    do.sendGenerateWithRequired(self, parentId, zoneId, optionalFields)
  File "C:\Panda3D-1.11.0-x64\direct\distributed\DistributedObjectAI.py", line 463, in sendGenerateWithRequired
    dg = self.dclass.aiFormatGenerate(
AssertionError: Distributed class ToontownDistrict doesn't have getter named getAllowAHNNLog to match required field allowAHNNLog at line 421 of E:\Toontown Fantasy\fantasy-panda\direct\src\dcparser\dcClass_ext.cxx
Press any key to continue . . .
```

This crashes the game...

**Comment by GracieLovelight** [comment]
Branch is no longer updated nor necessary.
