### ISSUE TITLE
Bug - DistributedNPCClerkAI:

### ISSUE THREAD

**Issue by GracieLovelight** [Arbitrium-Studios/Open-Fantasy#31]
```
Traceback (most recent call last):
  File "C:\Panda3D-1.11.0-x64\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Panda3D-1.11.0-x64\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\zacha\SynologyDrive\Toontown Fantasy\open-fantasy\toontown\ai\AIStart.py", line 78, in <module>
    run()
  File "C:\Users\zacha\SynologyDrive\Toontown Fantasy\open-fantasy\otp\ai\AIBase.py", line 202, in run
    self.taskMgr.run()
  File "C:\Panda3D-1.11.0-x64\direct\task\Task.py", line 546, in run
    self.step()
  File "C:\Panda3D-1.11.0-x64\direct\task\Task.py", line 497, in step
    self.mgr.poll()
  File "C:\Users\zacha\SynologyDrive\Toontown Fantasy\open-fantasy\toontown\toon\DistributedNPCClerkAI.py", line 68, in sendTimeoutMovie
    self.sendClearMovie(None)
  File "C:\Users\zacha\SynologyDrive\Toontown Fantasy\open-fantasy\toontown\toon\DistributedNPCClerkAI.py", line 74, in sendClearMovie
    self.busy.remove(avId)
ValueError: list.remove(x): x not in list
Press any key to continue . . .
```

To go with the previous error, I just noticed the District Server also crashed.

**Comment by DarthNihilus1** [comment]
Ah 
before self.busy.remove(avId) in the traceback
do if avId in self.busy:

**Comment by DarthNihilus1** [comment]
Any updates on this lol

**Comment by GracieLovelight** [comment]
This has been fixed!
