### ISSUE TITLE
Crash - Orbital Camera: 

### ISSUE THREAD

**Issue by GracieLovelight** [Arbitrium-Studios/Open-Fantasy#35]
When putting the game into full screen, the game crashes with this message:

```
Traceback (most recent call last):
  File "C:\Users\zacha\SynologyDrive\Toontown Fantasy\open-fantasy\otp\launcher\LauncherBase.py", line 158, in mainLoop
    self._runTaskManager()
  File "C:\Users\zacha\SynologyDrive\Toontown Fantasy\open-fantasy\otp\launcher\LauncherBase.py", line 138, in _runTaskManager
    taskMgr.run()
  File "C:\Panda3D-1.11.0-x64\direct\task\Task.py", line 546, in run
    self.step()
  File "C:\Panda3D-1.11.0-x64\direct\task\Task.py", line 497, in step
    self.mgr.poll()
  File "C:\Panda3D-1.11.0-x64\direct\showbase\EventManager.py", line 50, in eventLoopTask
    self.doEvents()
  File "C:\Panda3D-1.11.0-x64\direct\showbase\EventManager.py", line 44, in doEvents
    processFunc(dequeueFunc())
  File "C:\Panda3D-1.11.0-x64\direct\showbase\EventManager.py", line 100, in processEvent
    messenger.send(eventName, paramList)
  File "C:\Panda3D-1.11.0-x64\direct\showbase\Messenger.py", line 335, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Panda3D-1.11.0-x64\direct\showbase\Messenger.py", line 420, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "C:\Panda3D-1.11.0-x64\direct\gui\DirectButton.py", line 107, in commandFunc
    self['command'](*self['extraArgs'])
  File "C:\Panda3D-1.11.0-x64\direct\gui\DirectDialog.py", line 180, in <lambda>
    command = lambda s = self, v = value: s.buttonCommand(v)
  File "C:\Panda3D-1.11.0-x64\direct\gui\DirectDialog.py", line 339, in buttonCommand
    self['command'](value, *self['extraArgs'])
  File "C:\Users\zacha\SynologyDrive\Toontown Fantasy\open-fantasy\toontown\shtiker\DisplaySettingsDialog.py", line 464, in __applyDone
    if not self.changeDisplayProperties(
  File "C:\Users\zacha\SynologyDrive\Toontown Fantasy\open-fantasy\toontown\shtiker\DisplaySettingsDialog.py", line 521, in changeDisplayProperties
    if self.resetDisplayProperties(pipe, properties):
  File "C:\Users\zacha\SynologyDrive\Toontown Fantasy\open-fantasy\toontown\shtiker\DisplaySettingsDialog.py", line 627, in resetDisplayProperties
    NametagGlobals.setCamera(base.cam)
NameError: name 'NametagGlobals' is not defined
Press any key to continue . . .
```

**Comment by DarthNihilus1** [comment]
Looks like nametagglobals was never imported from panda3d.otp in that file?

**Comment by ThePlayerZero** [comment]
So, all I have to do is import NametagGlobals in DisplaySettingsDialog.py?

**Comment by DarthMDev** [comment]
can you test this again at some point i cant test it bc mac has a seperate issue with fullscreening 
Assertion failed: (result == 0), function lock, file mutexPosixImpl.I, line 99.
start-game.sh: line 6: 30855 Abort trap: 6           python3.10 -m toontown.launcher.QuickStartLauncher

**Comment by GracieLovelight** [comment]
This has been fixed or is invalid.
