### ISSUE TITLE
Bug - Clicking on the Kart Page crashes the game

### ISSUE THREAD

**Issue by GracieLovelight** [Arbitrium-Studios/Open-Fantasy#43]
When you click on the Kart Page in your Shtiker Book, it crashes your game while giving you this error in the game log:

```Traceback (most recent call last):
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\otp\launcher\LauncherBase.py", line 161, in mainLoop
    self._runTaskManager()
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\otp\launcher\LauncherBase.py", line 141, in _runTaskManager
    taskMgr.run()
  File "C:\Open-Panda\direct\task\Task.py", line 541, in run
    self.step()
  File "C:\Open-Panda\direct\task\Task.py", line 492, in step
    self.mgr.poll()
  File "C:\Open-Panda\direct\showbase\EventManager.py", line 50, in eventLoopTask
    self.doEvents()
  File "C:\Open-Panda\direct\showbase\EventManager.py", line 44, in doEvents
    processFunc(dequeueFunc())
  File "C:\Open-Panda\direct\showbase\EventManager.py", line 100, in processEvent
    messenger.send(eventName, paramList)
  File "C:\Open-Panda\direct\showbase\Messenger.py", line 335, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Open-Panda\direct\showbase\Messenger.py", line 420, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "C:\Open-Panda\direct\gui\DirectButton.py", line 107, in commandFunc
    self['command'](*self['extraArgs'])
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\toontown\shtiker\ShtikerBook.py", line 257, in goToPage
    self.setPage(page)
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\toontown\shtiker\ShtikerBook.py", line 363, in setPage
    page.enter()
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\toontown\shtiker\KartPage.py", line 30, in enter
    self.setMode(self.mode, 1)
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\toontown\shtiker\KartPage.py", line 216, in setMode
    self.updatePage()
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\toontown\shtiker\KartPage.py", line 220, in updatePage
    self.kartCustomizer.show()
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\toontown\shtiker\KartPage.py", line 291, in show
    self.kartViewer.show(list(self.avatar.getKartDNA()))
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\toontown\shtiker\KartPage.py", line 1269, in show
    self.refresh(dna)
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\toontown\shtiker\KartPage.py", line 1314, in refresh
    self.kartFrame = self.makeKartFrame()
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\toontown\shtiker\KartPage.py", line 1229, in makeKartFrame
    self.kart.generateKart(forGui=1)
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\toontown\racing\Kart.py", line 91, in generateKart
    self.__createLODKart(level)
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\toontown\racing\Kart.py", line 142, in __createLODKart
    self.geom[level] = loader.loadModel(kartBodyPath)
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\toontown\toonbase\ToontownLoader.py", line 76, in loadModel
    ret = Loader.Loader.loadModel(self, *args, **kw)
  File "C:\Open-Panda\direct\showbase\Loader.py", line 256, in loadModel
    node = self.loader.loadSync(Filename(modelPath), loaderOptions)
TypeError: expected str, bytes or os.PathLike object, not int```

**Comment by DarthMDev** [comment]
doesn't crash for me? closing for now
