### ISSUE TITLE
Crash - Entering Field Offices will crash the District.

### ISSUE THREAD

**Issue by GracieLovelight** [Arbitrium-Studios/Open-Fantasy#47]
Entering a Sellbot Field Office will crash the District you are playing in.

```Traceback (most recent call last):
  File "C:\Open-Panda\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Open-Panda\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\toontown\ai\AIStart.py", line 78, in <module>
    run()
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\otp\ai\AIBase.py", line 202, in run
    self.taskMgr.run()
  File "C:\Open-Panda\direct\task\Task.py", line 541, in run
    self.step()
  File "C:\Open-Panda\direct\task\Task.py", line 492, in step
    self.mgr.poll()
  File "C:\Open-Panda\direct\distributed\ConnectionRepository.py", line 612, in readerPollUntilEmpty
    while self.readerPollOnce():
  File "C:\Open-Panda\direct\distributed\ConnectionRepository.py", line 617, in readerPollOnce
    if self.checkDatagram():
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\toontown\cogdominium\DistributedCogdoInteriorAI.py", line 380, in setAvatarJoined
    self.fsm.request('Elevator')
  File "C:\Open-Panda\direct\fsm\ClassicFSM.py", line 281, in request
    self.__transition(aState,
  File "C:\Open-Panda\direct\fsm\ClassicFSM.py", line 230, in __transition
    self.__enter(aState, enterArgList)
  File "C:\Open-Panda\direct\fsm\ClassicFSM.py", line 216, in __enter
    aState.enter(argList)
  File "C:\Open-Panda\direct\fsm\State.py", line 200, in enter
    self.__enterFunc(*argList)
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\toontown\cogdominium\DistributedCogdoInteriorAI.py", line 486, in enterElevator
    self._game = self._createGame()
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\toontown\cogdominium\DistributedCogdoInteriorAI.py", line 527, in _createGame
    game.setExteriorZone(self.extZoneId)
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\toontown\cogdominium\DistCogdoMazeGameAI.py", line 43, in setExteriorZone
    self.createSuits()
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\toontown\cogdominium\DistCogdoMazeGameAI.py", line 67, in createSuits
    self.maxPickups = self._numSuits[0] * Globals.SuitData[0]['memos']
KeyError: 0
Press any key to continue . . .```

![image](https://user-images.githubusercontent.com/68795576/227755874-b6a779c4-6101-429f-9b32-dd994e0556c4.png)

**Comment by DarthMDev** [comment]
doesn't seem to happen anymore
