### ISSUE TITLE
(Development) Entering Sellbot Field Office crashes game

### ISSUE THREAD

**Issue by GracieLovelight** [Arbitrium-Studios/Open-Fantasy#64]
Entering a Sellbot Field Office crashes the game

```Traceback (most recent call last):
  File "E:\Toontown\Toontown Fantasy\Development Branch\otp\launcher\LauncherBase.py", line 158, in mainLoop
    self._runTaskManager()
  File "E:\Toontown\Toontown Fantasy\Development Branch\otp\launcher\LauncherBase.py", line 138, in _runTaskManager
    taskMgr.run()
  File "C:\Open-Panda\direct\task\Task.py", line 541, in run
    self.step()
  File "C:\Open-Panda\direct\task\Task.py", line 492, in step
    self.mgr.poll()
  File "C:\Open-Panda\direct\distributed\ConnectionRepository.py", line 612, in readerPollUntilEmpty
    while self.readerPollOnce():
  File "C:\Open-Panda\direct\distributed\ConnectionRepository.py", line 619, in readerPollOnce
    self.handleDatagram(self.private__di)
  File "E:\Toontown\Toontown Fantasy\Development Branch\otp\distributed\OTPClientRepository.py", line 2331, in handleDatagram
    self.handler(msgType, di)
  File "E:\Toontown\Toontown Fantasy\Development Branch\otp\distributed\OTPClientRepository.py", line 1824, in handlePlayGame
    self.handleGenerateWithRequired(di)
  File "E:\Toontown\Toontown Fantasy\Development Branch\otp\distributed\OTPClientRepository.py", line 2508, in handleGenerateWithRequired
    return self.__generateObject(
  File "E:\Toontown\Toontown Fantasy\Development Branch\otp\distributed\OTPClientRepository.py", line 2615, in __generateObject
    distObj = self.generateWithRequiredFields(
  File "C:\Open-Panda\direct\distributed\ClientRepositoryBase.py", line 268, in generateWithRequiredFields
    distObj.updateRequiredFields(dclass, di)
  File "C:\Open-Panda\direct\distributed\DistributedObject.py", line 343, in updateRequiredFields
    self.announceGenerate()
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\cogdominium\DistCogdoGame.py", line 110, in announceGenerate
    self.loadFSM.request('Loaded')
  File "C:\Open-Panda\direct\fsm\ClassicFSM.py", line 281, in request
    self.__transition(aState,
  File "C:\Open-Panda\direct\fsm\ClassicFSM.py", line 230, in __transition
    self.__enter(aState, enterArgList)
  File "C:\Open-Panda\direct\fsm\ClassicFSM.py", line 216, in __enter
    aState.enter(argList)
  File "C:\Open-Panda\direct\fsm\State.py", line 200, in enter
    self.__enterFunc(*argList)
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\cogdominium\DistCogdoMazeGame.py", line 52, in enterLoaded
    self.game.load(mazeFactory, self._numSuits, bossCode)
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\cogdominium\CogdoMazeGame.py", line 113, in load
    self._movie.load()
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\cogdominium\CogdoMazeGameMovies.py", line 81, in load
    self.clipPlane.node().setPlane(Plane(0, 0, 1, 0))
NameError: name 'Plane' is not defined
Press any key to continue . . .```

**Comment by DarthMDev** [comment]
Oh this might've been a me thing sorry ill look into what is actually needed

**Comment by GracieLovelight** [comment]
Thanks!
