### ISSUE TITLE
(Development) Crash in Battle

### ISSUE THREAD

**Issue by GracieLovelight** [Arbitrium-Studios/Open-Fantasy#65]
I encountered a crash in battle after choosing a gag.

```Traceback (most recent call last):
  File "E:\Toontown\Toontown Fantasy\Development Branch\otp\launcher\LauncherBase.py", line 158, in mainLoop
    self._runTaskManager()
  File "E:\Toontown\Toontown Fantasy\Development Branch\otp\launcher\LauncherBase.py", line 138, in _runTaskManager
    taskMgr.run()
  File "C:\Open-Panda\direct\task\Task.py", line 541, in run
    self.step()
  File "C:\Open-Panda\direct\task\Task.py", line 492, in step
    self.mgr.poll()
  File "C:\Open-Panda\direct\distributed\ConnectionRepository.py", line 612, in readerPollUntilEmpty
    while self.readerPollOnce():
  File "C:\Open-Panda\direct\distributed\ConnectionRepository.py", line 619, in readerPollOnce
    self.handleDatagram(self.private__di)
  File "E:\Toontown\Toontown Fantasy\Development Branch\otp\distributed\OTPClientRepository.py", line 2331, in handleDatagram
    self.handler(msgType, di)
  File "E:\Toontown\Toontown Fantasy\Development Branch\otp\distributed\OTPClientRepository.py", line 1828, in handlePlayGame
    self.handleUpdateField(di)
  File "C:\Open-Panda\direct\distributed\ClientRepositoryBase.py", line 443, in handleUpdateField
    self.__doUpdate(doId, di, ovUpdated)
  File "C:\Open-Panda\direct\distributed\ClientRepositoryBase.py", line 451, in __doUpdate
    do.dclass.receiveUpdate(do, di)
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\battle\DistributedBattleBase.py", line 388, in setState
    self.fsm.request(state, [globalClockDelta.localElapsedTime(timestamp)])
  File "C:\Open-Panda\direct\fsm\ClassicFSM.py", line 281, in request
    self.__transition(aState,
  File "C:\Open-Panda\direct\fsm\ClassicFSM.py", line 230, in __transition
    self.__enter(aState, enterArgList)
  File "C:\Open-Panda\direct\fsm\ClassicFSM.py", line 216, in __enter
    aState.enter(argList)
  File "C:\Open-Panda\direct\fsm\State.py", line 200, in enter
    self.__enterFunc(*argList)
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\battle\DistributedBattleBase.py", line 1448, in enterPlayMovie
    self.movie.play(ts, self.__handleMovieDone)
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\battle\Movie.py", line 244, in play
    sattacks, scam = self.__doSuitAttacks()
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\battle\Movie.py", line 1021, in __doSuitAttacks
    ival, camIval = MovieSuitAttacks.doSuitAttack(a)
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\battle\MovieSuitAttacks.py", line 270, in doSuitAttack
    camTrack = MovieCamera.chooseSuitShot(attack, suitTrack.getDuration())
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\battle\MovieCamera.py", line 382, in chooseSuitShot
    toon = target['toon']
TypeError: list indices must be integers or slices, not str
Press any key to continue . . .```

**Comment by GracieLovelight** [comment]
There appears to be another crash.

```Traceback (most recent call last):
  File "E:\Toontown\Toontown Fantasy\Development Branch\otp\launcher\LauncherBase.py", line 158, in mainLoop
    self._runTaskManager()
  File "E:\Toontown\Toontown Fantasy\Development Branch\otp\launcher\LauncherBase.py", line 138, in _runTaskManager
    taskMgr.run()
  File "C:\Open-Panda\direct\task\Task.py", line 541, in run
    self.step()
  File "C:\Open-Panda\direct\task\Task.py", line 492, in step
    self.mgr.poll()
  File "C:\Open-Panda\direct\distributed\ConnectionRepository.py", line 612, in readerPollUntilEmpty
    while self.readerPollOnce():
  File "C:\Open-Panda\direct\distributed\ConnectionRepository.py", line 619, in readerPollOnce
    self.handleDatagram(self.private__di)
  File "E:\Toontown\Toontown Fantasy\Development Branch\otp\distributed\OTPClientRepository.py", line 2331, in handleDatagram
    self.handler(msgType, di)
  File "E:\Toontown\Toontown Fantasy\Development Branch\otp\distributed\OTPClientRepository.py", line 1828, in handlePlayGame
    self.handleUpdateField(di)
  File "C:\Open-Panda\direct\distributed\ClientRepositoryBase.py", line 443, in handleUpdateField
    self.__doUpdate(doId, di, ovUpdated)
  File "C:\Open-Panda\direct\distributed\ClientRepositoryBase.py", line 451, in __doUpdate
    do.dclass.receiveUpdate(do, di)
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\battle\DistributedBattleBase.py", line 388, in setState
    self.fsm.request(state, [globalClockDelta.localElapsedTime(timestamp)])
  File "C:\Open-Panda\direct\fsm\ClassicFSM.py", line 281, in request
    self.__transition(aState,
  File "C:\Open-Panda\direct\fsm\ClassicFSM.py", line 230, in __transition
    self.__enter(aState, enterArgList)
  File "C:\Open-Panda\direct\fsm\ClassicFSM.py", line 216, in __enter
    aState.enter(argList)
  File "C:\Open-Panda\direct\fsm\State.py", line 200, in enter
    self.__enterFunc(*argList)
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\battle\DistributedBattleBase.py", line 1448, in enterPlayMovie
    self.movie.play(ts, self.__handleMovieDone)
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\battle\Movie.py", line 244, in play
    sattacks, scam = self.__doSuitAttacks()
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\battle\Movie.py", line 1034, in __doSuitAttacks
    if targetField['died'] and targetField['toon'].doId == base.localAvatar.doId:
TypeError: list indices must be integers or slices, not str
Press any key to continue . . .```
