### ISSUE TITLE
(development_playground-renames) Playground

### ISSUE THREAD

**Issue by GracieLovelight** [Arbitrium-Studios/Open-Fantasy#86]
Entering the Foggy Fjord playground crashes the game. Here's what the game log says:

```
Traceback (most recent call last):
  File "E:\Toontown\Toontown Fantasy\Development Branch\otp\launcher\LauncherBase.py", line 158, in mainLoop
    self._runTaskManager()
  File "E:\Toontown\Toontown Fantasy\Development Branch\otp\launcher\LauncherBase.py", line 138, in _runTaskManager
    taskMgr.run()
  File "C:\Open-Panda\direct\task\Task.py", line 541, in run
    self.step()
  File "C:\Open-Panda\direct\task\Task.py", line 492, in step
    self.mgr.poll()
  File "C:\Open-Panda\direct\distributed\ConnectionRepository.py", line 612, in readerPollUntilEmpty
    while self.readerPollOnce():
  File "C:\Open-Panda\direct\distributed\ConnectionRepository.py", line 619, in readerPollOnce
    self.handleDatagram(self.private__di)
  File "E:\Toontown\Toontown Fantasy\Development Branch\otp\distributed\OTPClientRepository.py", line 2331, in handleDatagram
    self.handler(msgType, di)
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\hood\QuietZoneState.py", line 189, in handleWaitForQuietZoneResponse
    base.cr.handlePlayGame(msgType, di)
  File "E:\Toontown\Toontown Fantasy\Development Branch\otp\distributed\OTPClientRepository.py", line 1832, in handlePlayGame
    self.handleMessageType(msgType, di)
  File "E:\Toontown\Toontown Fantasy\Development Branch\otp\distributed\OTPClientRepository.py", line 2212, in handleMessageType
    self.gotInterestDoneMessage(di)
  File "E:\Toontown\Toontown Fantasy\Development Branch\otp\distributed\OTPClientRepository.py", line 2251, in gotInterestDoneMessage
    self.handleInterestDoneMessage(di)
  File "C:\Open-Panda\direct\distributed\DoInterestManager.py", line 641, in handleInterestDoneMessage
    messenger.send(event)
  File "C:\Open-Panda\direct\showbase\Messenger.py", line 335, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Open-Panda\direct\showbase\Messenger.py", line 420, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\distributed\ToontownClientRepository.py", line 1241, in _handleEmuSetZoneDone
    messenger.send(event)
  File "C:\Open-Panda\direct\showbase\Messenger.py", line 335, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Open-Panda\direct\showbase\Messenger.py", line 420, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\hood\QuietZoneState.py", line 247, in _handleQuietZoneComplete
    self.fsm.request('waitForZoneRedirect')
  File "C:\Open-Panda\direct\fsm\ClassicFSM.py", line 281, in request
    self.__transition(aState,
  File "C:\Open-Panda\direct\fsm\ClassicFSM.py", line 230, in __transition
    self.__enter(aState, enterArgList)
  File "C:\Open-Panda\direct\fsm\ClassicFSM.py", line 216, in __enter
    aState.enter(argList)
  File "C:\Open-Panda\direct\fsm\State.py", line 200, in enter
    self.__enterFunc(*argList)
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\hood\QuietZoneState.py", line 293, in enterWaitForZoneRedirect
    self.fsm.request('waitForSetZoneResponse')
  File "C:\Open-Panda\direct\fsm\ClassicFSM.py", line 281, in request
    self.__transition(aState,
  File "C:\Open-Panda\direct\fsm\ClassicFSM.py", line 230, in __transition
    self.__enter(aState, enterArgList)
  File "C:\Open-Panda\direct\fsm\ClassicFSM.py", line 216, in __enter
    aState.enter(argList)
  File "C:\Open-Panda\direct\fsm\State.py", line 200, in enter
    self.__enterFunc(*argList)
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\hood\QuietZoneState.py", line 312, in enterWaitForSetZoneResponse
    messenger.send(
  File "C:\Open-Panda\direct\showbase\Messenger.py", line 335, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Open-Panda\direct\showbase\Messenger.py", line 420, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\distributed\PlayGame.py", line 361, in handleWaitForSetZoneResponse
    self.hood.loadLoader(requestStatus)
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\hood\ToonHood.py", line 68, in loadLoader
    self.loader.load()
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\safezone\DDSafeZoneLoader.py", line 22, in load
    SafeZoneLoader.SafeZoneLoader.load(self)
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\safezone\SafeZoneLoader.py", line 51, in load
    self.createSafeZone(self.dnaFile)
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\safezone\SafeZoneLoader.py", line 85, in createSafeZone
    loader.loadDNAFile(self.hood.dnaStore, self.safeZoneStorageDNAFile)
  File "E:\Toontown\Toontown Fantasy\Development Branch\toontown\toonbase\ToontownLoader.py", line 109, in loadDNAFile
    ret = loadDNAFile(dnaStore, dnaFile, CSDefault, 0)
AssertionError: !is_empty() at line 2000 of E:\Toontown\Panda3D\panda3d\built_x64\include\nodePath.I
Press any key to continue . . .
```

If you teleport to the bugged playground, it will revert you back to the previous one you were in. However, entering the playground's street does not crash you until you enter the tunnel and you won't be able to get back into the previous playground.

The playgrounds that crash you are...:

- [ ] Foggy Fjord
- [ ] Harmony Haven

**Comment by GracieLovelight** [comment]
My best guess is Windows didn't tell me where all of the files for each playground are. So, Toontown Stadium loads with broken textures but the playground files are misconfigured or not renamed somewhere. My conclusion was because of [this](https://www.youtube.com/watch?v=wcsxRhblrkM)!
